<a href="https://colab.research.google.com/github/shivani5015/Deep_learning_journey/blob/main/1.Ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# ANN (Artificial Neural Network)
## 1. Concept
* DL model built for **tabular / structured data** (CSV files).
* Flow `Input Layer` ➔ `Hidden Layers` ➔ `Output Layer`.

## 2.Execution Loop
1. **Forward Pass (Predict):** Multiplies inputs & weights, adds bias, and runs activation to predict.
2. **Loss Check (Compare):** Calculates error (actual vs predicted).
   * Classification ➔ Cross-Entropy
   * Regression ➔ MAE / MSE
3. **Backprop(Learn and update):** Passes error backwards to adjust weights using an optimizer (`Adam` / `SGD`).

#  Activation Functions
* **ReLU:** Hidden layers default ($[0, \infty)$).
* **Leaky ReLU:** Fixes dying ReLU problem.($[-\infty, \infty)$).
* **PReLU:** Trainable negative slope parameter.($[-\infty, \infty)$).
* **Sigmoid:** Binary classification output ($(0, 1)$).
* **Softmax:** Multi-class classification output ($(0, 1)$).
* **Tanh:** Zero-centered hidden layers ($(-1, 1)$).

# Optimizers

Optimizers is used to update weight and parameter of neural network to minimise loss and improve accuracy.

* **SGD (Stochastic Gradient Descent):** it updates weights using a mini batch; simple but noisy ,slow to converge.
* **Momentum:** improves SGD by using previous weight to improves accuracy.
* **NAG (Nesterov Accelerated Gradient):** it first looks ahead at future position before taking a step, preventing overshooting.
* **AdaGrad:** it lower learning rates for frequent features while giving larger updates to rare features good for sparse data.
* **RMSprop:** Fixes AdaGrad's learning rate problem using an exponential moving average.
* **Adam (Adaptive Moment Estimation):** Combines Momentum + RMSprop; default go-to optimizer for almost every deep learning model.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("/content/Attrition - Attrition.csv")  #load data
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [ ]:
import tensorflow as tf       #import libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.metrics import accuracy_score

In [ ]:
df=df.dropna()

In [ ]:
x=df.drop(columns=['Attrition'],axis=1)  #divide data
y=df['Attrition']

In [ ]:
categorical_features=['BusinessTravel','Department','EducationField','Gender','JobRole','MaritalStatus','Over18','OverTime']

In [ ]:
x_encode=pd.get_dummies(x,columns=categorical_features,drop_first=True)

In [ ]:
x_encode=x_encode.astype(int)

In [ ]:
lb=LabelEncoder()
y_encode=lb.fit_transform(y)
y_encode

array([1, 0, 1, ..., 0, 0, 0])

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x_encode,y_encode,test_size=0.2,random_state=42)

In [ ]:
x_train.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
1097,24,350,21,2,1,1551,3,57,2,1,...,1,0,0,0,0,0,0,0,0,0
727,18,287,5,2,1,1012,2,73,3,1,...,0,0,0,0,1,0,0,0,1,0
254,29,1247,20,2,1,349,4,45,3,2,...,0,0,0,0,0,1,0,0,0,0
1175,39,492,12,3,1,1654,4,66,3,2,...,0,0,1,0,0,0,0,1,0,0
1341,31,311,20,3,1,1881,2,89,3,2,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
sc=StandardScaler()
x_train_sc=sc.fit_transform(x_train)
x_test_sc=sc.transform(x_test)

In [ ]:
model=tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=128,activation='relu',input_dim=x_train_sc.shape[1]),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=64,activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=1,activation='sigmoid')
])

In [ ]:
loss_fn = tf.keras.losses.BinaryCrossentropy()
optimizer = tf.keras.optimizers.SGD(learning_rate=0.001, momentum=0.9, nesterov=True)

model.compile(optimizer=optimizer, loss=loss_fn, metrics=['accuracy'])

In [ ]:
model.fit(x_train_sc, y_train, epochs=50, batch_size=8, validation_split=0.1)

Epoch 1/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.7703 - loss: 0.5424 - val_accuracy: 0.7966 - val_loss: 0.5136
Epoch 2/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8299 - loss: 0.4560 - val_accuracy: 0.7966 - val_loss: 0.4770
Epoch 3/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8374 - loss: 0.4246 - val_accuracy: 0.7966 - val_loss: 0.4604
Epoch 4/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8431 - loss: 0.4052 - val_accuracy: 0.7966 - val_loss: 0.4371
Epoch 5/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8497 - loss: 0.3910 - val_accuracy: 0.8136 - val_loss: 0.4243
Epoch 6/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8450 - loss: 0.3710 - val_accuracy: 0.8136 - val_loss: 0.4212
Epoch 7/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8497 - loss: 0.3751 - val_accuracy: 0.8051 - val_loss: 0.4129
Epoch 8/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8592 - loss: 0.3602 - val_accuracy: 0.8051 - val_loss: 0.4073
Epoch 9/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8620 - loss: 0.3537 - val_accuracy: 0.8305 - val_loss: 0.4030
Epoch 10/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8667 - loss: 0.3406 - val_accuracy: 0.8220 - val_loss: 0.4052
Epoch 11/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8752 - loss: 0.3158 - val_accuracy: 0.8220 - val_loss: 0.3990
Epoch 12/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8686 - loss: 0.3207 - val_accuracy: 0.8305 - val_loss: 0.4033
Epoch 13/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8743 - loss: 0.3243 - val_accuracy: 0.8305 - val_loss: 0.4027
Epoch 14/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8922 - loss: 0.2958 - val_accuracy: 0.8305 - val_loss: 0.4045
Epoch 15/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8752 - loss: 0.3155 - val_accuracy: 0.7966 - val_loss: 0.3956
Epoch 16/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8932 - loss: 0.2991 - val_accuracy: 0.8136 - val_loss: 0.3979
Epoch 17/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8819 - loss: 0.2980 - val_accuracy: 0.8220 - val_loss: 0.4039
Epoch 18/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8904 - loss: 0.2941 - val_accuracy: 0.8136 - val_loss: 0.4074
Epoch 19/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8866 - loss: 0.2834 - val_accuracy: 0.8136 - val_loss: 0.4049
Epoch 20/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8875 - loss: 0.2844 - val_accuracy: 0.8136 - val_loss: 0.4091
Epoch 21/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8922 - loss: 0.2628 - val_accuracy: 0.8136 - val_loss: 0.4076
Epoch 22/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8932 - loss: 0.2724 - val_accuracy: 0.7881 - val_loss: 0.4107
Epoch 23/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8989 - loss: 0.2524 - val_accuracy: 0.8051 - val_loss: 0.4190
Epoch 24/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9036 - loss: 0.2515 - val_accuracy: 0.7881 - val_loss: 0.4207
Epoch 25/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8941 - loss: 0.2603 - val_accuracy: 0.7797 - val_loss: 0.4205
Epoch 26/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8960 - loss: 0.2643 - val_accuracy: 0.7881 - val_loss: 0.4253
Epoch 27/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8998 - loss: 0.2504 - val_accuracy: 0.7797 - val_loss: 0.4282
Epoch 28/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8913 - loss: 0.2584 - val_accuracy: 0.7797 - val_loss: 0.4295
Epoch 29/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9055 - loss: 0.2508 - val_accuracy: 0.7797 - val_loss: 0.4313
Epoch 30/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9102 - loss: 0.2321 - val_accuracy: 0.7712 - val_loss: 0.4311
Epoch 31/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9074 - loss: 0.2425 - val_accuracy: 0.7797 - val_loss: 0.4342
Epoch 32/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8989 - loss: 0.2501 - val_accuracy: 0.7881 - val_loss: 0.4268
Epoch 33/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9121 - loss: 0.2325 - val_accuracy: 0.7881 - val_loss: 0.4258
Epoch 34/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9140 - loss: 0.2262 - val_accuracy: 0.7881 - val_loss: 0.4316
Epoch 35/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9102 - loss: 0.2202 - val_accuracy: 0.7797 - val_loss: 0.4342
Epoch 36/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9083 - loss: 0.2367 - val_accuracy: 0.7881 - val_loss: 0.4329
Epoch 37/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9130 - loss: 0.2190 - val_accuracy: 0.7797 - val_loss: 0.4405
Epoch 38/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9045 - loss: 0.2275 - val_accuracy: 0.7797 - val_loss: 0.4409
Epoch 39/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9253 - loss: 0.1978 - val_accuracy: 0.7881 - val_loss: 0.4511
Epoch 40/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9074 - loss: 0.2069 - val_accuracy: 0.7881 - val_loss: 0.4531
Epoch 41/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9130 - loss: 0.2140 - val_accuracy: 0.7966 - val_loss: 0.4540
Epoch 42/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9102 - loss: 0.2079 - val_accuracy: 0.7797 - val_loss: 0.4443
Epoch 43/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9253 - loss: 0.1902 - val_accuracy: 0.7966 - val_loss: 0.4582
Epoch 44/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9206 - loss: 0.2075 - val_accuracy: 0.7797 - val_loss: 0.4595
Epoch 45/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9121 - loss: 0.2211 - val_accuracy: 0.7797 - val_loss: 0.4572
Epoch 46/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9234 - loss: 0.1977 - val_accuracy: 0.7881 - val_loss: 0.4603
Epoch 47/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9234 - loss: 0.1871 - val_accuracy: 0.7881 - val_loss: 0.4647
Epoch 48/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9178 - loss: 0.1952 - val_accuracy: 0.7881 - val_loss: 0.4658
Epoch 49/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9225 - loss: 0.1896 - val_accuracy: 0.7881 - val_loss: 0.4715
Epoch 50/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9291 - loss: 0.1948 - val_accuracy: 0.7966 - val_loss: 0.4741

In [ ]:
loss, accuracy = model.evaluate(x_test_sc, y_test)
print(f"test_loss={loss:.4f}, test_accuracy={accuracy:.4f}")

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8673 - loss: 0.3695
test_loss=0.3695, test_accuracy=0.8673