<a href="https://colab.research.google.com/github/shivani5015/Deep_learning_journey/blob/main/Text_Representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Text Representation**
- 1. Bag of words ==> we use countvectorization
- 2. N-grams
- 3. TF-IDF

In [ ]:
#1.Bag of world
import numpy as np
import pandas as pd

In [ ]:
df=pd.DataFrame({'text':['people watch cricket',
                         'player was player',
                         'people write comment',
                         'cricket play comment'],
                 'output':[1,1,0,0]})

In [ ]:
df

                   text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [ ]:
#people watch cricket player was write comment play
(11100000),(00021000),(10000110),(00100011)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
bow=cv.fit_transform(df['text'])

In [ ]:
#vacob
print(cv.vocabulary_)

{'people': 2, 'watch': 6, 'cricket': 1, 'player': 4, 'was': 5, 'write': 7, 'comment': 0, 'play': 3}

In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 0 0 0 1 0]]
[[0 0 0 0 2 1 0 0]]

In [ ]:
cv.transform(['cricket watch and write comment of cricket comment']).toarray()

array([[2, 2, 0, 0, 0, 0, 1, 1]])

In [ ]:
#2. N-grams
#v=CountVectorizer(ngram_range=(1,2)) #phale single single world lo, fir 2-2 ke pire lo
v=CountVectorizer(ngram_range=(2,2))
bow=v.fit_transform(df['text'])
df['text']

0    people watch cricket
1       player was player
2    people write comment
3    cricket play comment
Name: text, dtype: object

In [ ]:
print(v.vocabulary_)

{'people watch': 1, 'watch cricket': 6, 'player was': 4, 'was player': 5, 'people write': 2, 'write comment': 7, 'cricket play': 0, 'play comment': 3}

 # **TF(Term Frequencey) - IDF(Inverse Document Frequencey):-**

TF-IDF is calculated by multiplying **TF (Term Frequency)** and **IDF (Inverse Document Frequency)**.

### Formula

$$
TF\text{-}IDF(t,d) = TF(t,d) \times IDF(t)
$$

Where:

- $t$ = Term (word)
- $d$ = Document
- $TF(t,d)$ = Term Frequency of term $t$ in document $d$
- $IDF(t)$ = Inverse Document Frequency of term $t$
$$

In [ ]:
df

                   text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()
tf.fit_transform(df['text']).toarray()

array([[0.        , 0.52640543, 0.52640543, 0.        , 0.        ,
        0.        , 0.66767854, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.89442719,
        0.4472136 , 0.        , 0.        ],
       [0.52640543, 0.        , 0.52640543, 0.        , 0.        ,
        0.        , 0.        , 0.66767854],
       [0.52640543, 0.52640543, 0.        , 0.66767854, 0.        ,
        0.        , 0.        , 0.        ]])

In [ ]:
print(tf.idf_)
print(tf.get_feature_names_out())

[1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073]
['comment' 'cricket' 'people' 'play' 'player' 'was' 'watch' 'write']